version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-ecommerce}
      MYSQL_USER: ${DB_USERNAME:-ecom_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-ecom_pass}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpass}
    ports:
      - '${DB_PORT:-3306}:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
    driver: local
